### ISSUE TITLE
Coroot-node-agent 1.23.7 memory utilization spikes leading to OOM

### ISSUE THREAD

**Issue by gwyn-bl** [coroot/coroot-node-agent#175]
Hi!
After upgrading to coroot-node-agent version 1.23.7 it is encountering high memory usage spikes that leading to OOM

```
resources:
    requests:
      cpu: "2"
      memory: "4Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
```

![Image](https://github.com/user-attachments/assets/e706ed14-470b-4464-8ec8-04ae3464cf2c)
![Image](https://github.com/user-attachments/assets/f100e8af-e3b7-4e36-889c-9e10f2e8fd08)

**Comment by apetruhin** [comment]
Thank you for the report.

Could you please pick an affected pod (or a few) and dump the memory profile(s):
```
kubectl -n coroot exec -t coroot-node-agent-bck98 -- curl -o - 127.0.0.1:10300/debug/pprof/heap > mem_profile.tgz
```
Depending on the setup, the port could be `80` instead of `10300`.

**Comment by apetruhin** [comment]
Profiles are broken for some reason:
```
go tool pprof Downloads/mem_profile.tgz       
Downloads/mem_profile.tgz: decompressing profile: flate: corrupt input before offset 358
failed to fetch any source profiles
```
Could you please show me the exact command you used to dump them?

**Comment by apetruhin** [comment]
I don't see anything suspicious in this profile.
Could you please dump a few more from the pods that are currently consuming a large amount of memory?

**Comment by Gakhramanzode** [comment]
Hi!

I’m experiencing a similar issue after install ghcr.io/coroot/coroot-node-agent:1.23.11. My pods are also encountering high memory usage spikes, leading to OOM (Out of Memory) errors.

Here are the resource limits I’ve set:
```yaml
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:     1
      memory:  2Gi
```
Following the advice from this thread, I’ve captured a memory profile from one of the affected pods. You can find the profile here: https://drive.google.com/file/d/1EFkTcqI5XnuwIWz2y6MFlP_0XU5riH73/view?usp=drive_link

Let me know if you need any additional information or logs to help investigate this issue.

Thanks!
