### ISSUE TITLE
Only containerD is shown in application

### ISSUE THREAD

**Issue by Schaudhari7565** [coroot/coroot-node-agent#5]
As per documents and installation, after installing coroot and agent, prometheus was attached properly and only visible application was containerD any help appreciated

**Comment by apetruhin** [comment]
@Schaudhari7565, please attach logs of the agent

**Comment by Schaudhari7565** [comment]
[corootnodeagent-n4cbb.txt](https://github.com/coroot/coroot-node-agent/files/9678273/corootnodeagent-n4cbb.txt)
Attached is the logs from one of the agent

**Comment by Schaudhari7565** [comment]
manifest for agent 

```
---
# Source: corootnodeagent/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: coroot
  labels:
    chart: "corootnodeagent-1.0.0"
    release: "corootnodeagent"
    heritage: "Helm"
  name: corootnodeagent
spec:
  selector:
    matchLabels:
      app: corootnodeagent
      group: observability
      provider: tools
  template:
    metadata:
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
      labels:
        app: corootnodeagent
        group: observability
        provider: tools
    spec:
      imagePullSecrets:
        - name: regcred
      tolerations:
        - operator: Exists
      hostPID: true
      containers:
        - name: corootnodeagent
          image: "ghcr.io/coroot/coroot-node-agent:latest"
          imagePullPolicy: "IfNotPresent"
          args: ["--cgroupfs-root", "/host/sys/fs/cgroup"]
          ports:
            - name: http
              containerPort: 80
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/sys/fs/cgroup
              name: cgroupfs
              readOnly: true
            - mountPath: /sys/kernel/debug
              name: debugfs
              readOnly: false
      volumes:
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroupfs
        - hostPath:
            path: /sys/kernel/debug
          name: debugfs

```
